# Generated by Django 5.1.1 on 2024-10-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Office_System', '0002_alter_student_expelled_alter_student_hall_clearance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examregistration',
            name='token',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
