# Generated by Django 5.0.6 on 2024-11-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Office_System', '0002_alter_student_expelled_alter_student_hall_clearance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
        migrations.AddField(
            model_name='exam',
            name='courses',
            field=models.ManyToManyField(related_name='exams', to='Exam_Office_System.course'),
        ),
        migrations.RemoveField(
            model_name='exam',
            name='examiner1',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='examiner2',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='examiner3',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='invigilator',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='question_creator',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='translator',
        ),
        migrations.AddField(
            model_name='exam',
            name='examiner1',
            field=models.ManyToManyField(related_name='exam1_exams', to='Exam_Office_System.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='examiner2',
            field=models.ManyToManyField(related_name='exam2_exams', to='Exam_Office_System.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='examiner3',
            field=models.ManyToManyField(related_name='exam3_exams', to='Exam_Office_System.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='invigilator',
            field=models.ManyToManyField(related_name='invigilated_exams', to='Exam_Office_System.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='moderator',
            field=models.ManyToManyField(related_name='moderated_exams', to='Exam_Office_System.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='question_creator',
            field=models.ManyToManyField(related_name='question_created_exams', to='Exam_Office_System.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='translator',
            field=models.ManyToManyField(related_name='translated_exams', to='Exam_Office_System.teacher'),
        ),
    ]
