# Generated by Django 5.1.2 on 2024-11-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Office_System', '0003_sickbed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(choices=[('Semester', 'Semester'), ('Yearly', 'Yearly')], max_length=20)),
                ('class_start_date', models.DateField()),
                ('class_end_date', models.DateField()),
                ('exam_start_date', models.DateField()),
                ('exam_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.CharField(default='Pro Vice Chancellor', max_length=255)),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('notification_title', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_message', models.TextField(blank=True, null=True)),
                ('notification_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('public_notice_title', models.CharField(blank=True, max_length=255, null=True)),
                ('public_notice_content', models.TextField(blank=True, null=True)),
                ('public_notice_published_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
