# Generated by Django 5.0.6 on 2024-11-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Office_System', '0003_remove_marksheetapplication_application_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksheetapplication',
            name='registration_type',
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='registration_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Retake', 'Retake')], help_text='Type of registration: Regular or Retake.', max_length=20),
        ),
    ]
