# Generated by Django 5.1.1 on 2024-10-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Office_System', '0003_examregistration_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examregistration',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
