# Generated by Django 5.0.6 on 2024-11-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Office_System', '0004_alter_exam_examiner1_alter_exam_examiner2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='examiner1',
            field=models.ManyToManyField(related_name='exam1_exams', to='Exam_Office_System.teacher'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='examiner2',
            field=models.ManyToManyField(related_name='exam2_exams', to='Exam_Office_System.teacher'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='examiner3',
            field=models.ManyToManyField(related_name='exam3_exams', to='Exam_Office_System.teacher'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='invigilator',
            field=models.ManyToManyField(related_name='invigilated_exams', to='Exam_Office_System.teacher'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='moderator',
            field=models.ManyToManyField(related_name='moderated_exams', to='Exam_Office_System.teacher'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_creator',
            field=models.ManyToManyField(related_name='question_created_exams', to='Exam_Office_System.teacher'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='translator',
            field=models.ManyToManyField(related_name='translated_exams', to='Exam_Office_System.teacher'),
        ),
    ]
