# Generated by Django 5.0.6 on 2024-10-31 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Office_System', '0002_alter_student_expelled_alter_student_hall_clearance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksheetapplication',
            name='application_date',
        ),
        migrations.AddField(
            model_name='marksheetapplication',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Retake', 'Retake')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='marksheetapplication',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_Office_System.exam'),
        ),
        migrations.AlterField(
            model_name='marksheetapplication',
            name='payment_method',
            field=models.CharField(default='Regular', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marksheetapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='marksheetapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_Office_System.student'),
        ),
        migrations.AlterField(
            model_name='marksheetapplication',
            name='token',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
