# Generated by Django 4.2.7 on 2024-11-10 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Exam_Office_System', '0002_alter_student_expelled_alter_student_hall_clearance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='answer_scripts/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Graded', 'Graded'), ('Archived', 'Archived')], default='Pending', max_length=20)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_scripts', to='Exam_Office_System.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_scripts', to='Exam_Office_System.student')),
            ],
        ),
        migrations.CreateModel(
            name='GradingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_graded', models.BooleanField(default=False)),
                ('grading_started_at', models.DateTimeField(blank=True, null=True)),
                ('grading_completed_at', models.DateTimeField(blank=True, null=True)),
                ('answer_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_status', to='Answer_Script_Management.answerscript')),
            ],
        ),
        migrations.CreateModel(
            name='GradingDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discrepancy_found', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='Answer_Script_Management.answerscript')),
                ('examiner1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancy_examiner1', to='Exam_Office_System.teacher')),
                ('examiner2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancy_examiner2', to='Exam_Office_System.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ExaminerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examiner_assignments', to='Exam_Office_System.exam')),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exams', to='Exam_Office_System.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerScriptReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_comments', models.TextField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('answer_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Answer_Script_Management.answerscript')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='Exam_Office_System.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerScriptGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('answer_script', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading', to='Answer_Script_Management.answerscript')),
                ('examiner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_answer_scripts', to='Exam_Office_System.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerScriptArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('reason_for_archiving', models.TextField()),
                ('answer_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='Answer_Script_Management.answerscript')),
            ],
        ),
    ]
