# Generated by Django 4.2.7 on 2024-11-10 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Office_System', '0002_alter_student_expelled_alter_student_hall_clearance_and_more'),
        ('Answer_Script_Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalizedAnswerScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.IntegerField()),
                ('status', models.CharField(choices=[('Finalized', 'Finalized'), ('Not Finalized', 'Not Finalized')], default='Not Finalized', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='answerscriptgrading',
            name='answer_script',
        ),
        migrations.RemoveField(
            model_name='answerscriptgrading',
            name='examiner',
        ),
        migrations.RemoveField(
            model_name='answerscriptreview',
            name='answer_script',
        ),
        migrations.RemoveField(
            model_name='answerscriptreview',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='examinerassignment',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examinerassignment',
            name='examiner',
        ),
        migrations.RemoveField(
            model_name='gradingstatus',
            name='answer_script',
        ),
        migrations.RenameField(
            model_name='answerscript',
            old_name='file',
            new_name='script_file',
        ),
        migrations.RemoveField(
            model_name='answerscript',
            name='status',
        ),
        migrations.RemoveField(
            model_name='answerscript',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='gradingdiscrepancy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gradingdiscrepancy',
            name='discrepancy_found',
        ),
        migrations.RemoveField(
            model_name='gradingdiscrepancy',
            name='examiner1',
        ),
        migrations.RemoveField(
            model_name='gradingdiscrepancy',
            name='examiner2',
        ),
        migrations.RemoveField(
            model_name='gradingdiscrepancy',
            name='resolution_comments',
        ),
        migrations.RemoveField(
            model_name='gradingdiscrepancy',
            name='resolved',
        ),
        migrations.AddField(
            model_name='answerscript',
            name='examiner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_answer_scripts', to='Exam_Office_System.teacher'),
        ),
        migrations.AddField(
            model_name='answerscript',
            name='grading_status',
            field=models.CharField(choices=[('Not Graded', 'Not Graded'), ('Graded', 'Graded')], default='Not Graded', max_length=20),
        ),
        migrations.AddField(
            model_name='answerscript',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingdiscrepancy',
            name='discrepancy_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='gradingdiscrepancy',
            name='examiner1_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gradingdiscrepancy',
            name='examiner2_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gradingdiscrepancy',
            name='examiner3_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gradingdiscrepancy',
            name='answer_script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_discrepancies', to='Answer_Script_Management.answerscript'),
        ),
        migrations.DeleteModel(
            name='AnswerScriptArchive',
        ),
        migrations.DeleteModel(
            name='AnswerScriptGrading',
        ),
        migrations.DeleteModel(
            name='AnswerScriptReview',
        ),
        migrations.DeleteModel(
            name='ExaminerAssignment',
        ),
        migrations.DeleteModel(
            name='GradingStatus',
        ),
        migrations.AddField(
            model_name='finalizedanswerscript',
            name='answer_script',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalized_script', to='Answer_Script_Management.answerscript'),
        ),
    ]
