# Generated by Django 4.2.7 on 2024-11-14 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Office_System', '0002_alter_student_expelled_alter_student_hall_clearance_and_more'),
        ('Answer_Script_Management', '0002_finalizedanswerscript_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptEvaluationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_given', models.IntegerField()),
                ('evaluation_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gradingdiscrepancy',
            name='answer_script',
        ),
        migrations.RemoveField(
            model_name='answerscript',
            name='examiner',
        ),
        migrations.RemoveField(
            model_name='answerscript',
            name='grading_status',
        ),
        migrations.RemoveField(
            model_name='answerscript',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='answerscript',
            name='script_file',
        ),
        migrations.AddField(
            model_name='answerscript',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answerscript',
            name='examiner1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examiner1_scripts', to='Exam_Office_System.teacher'),
        ),
        migrations.AddField(
            model_name='answerscript',
            name='examiner2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examiner2_scripts', to='Exam_Office_System.teacher'),
        ),
        migrations.AddField(
            model_name='answerscript',
            name='examiner3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examiner3_scripts', to='Exam_Office_System.teacher'),
        ),
        migrations.AddField(
            model_name='answerscript',
            name='flagged_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answerscript',
            name='marks_examiner1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answerscript',
            name='marks_examiner2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answerscript',
            name='marks_examiner3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FinalizedAnswerScript',
        ),
        migrations.DeleteModel(
            name='GradingDiscrepancy',
        ),
        migrations.AddField(
            model_name='scriptevaluationlog',
            name='answer_script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_logs', to='Answer_Script_Management.answerscript'),
        ),
        migrations.AddField(
            model_name='scriptevaluationlog',
            name='examiner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_Office_System.teacher'),
        ),
    ]
