# Configuration file for the Sphinx documentation builder.

import os
import sys
import django

# -- Path setup --------------------------------------------------------------

# Add the project root directory to sys.path
# Adjust the path according to your project structure
sys.path.insert(0, os.path.abspath('../'))

# Set the Django settings module
os.environ['DJANGO_SETTINGS_MODULE'] = 'myproject.settings'  # Replace with your actual settings module

# Initialize Django
django.setup()

# -- Project information -----------------------------------------------------

project = 'Exam Office Management System'
copyright = '2024, Mahfuz Anam'
author = 'Mahfuz Anam'
release = '1.0.0'

# -- General configuration ---------------------------------------------------

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx_autodoc_typehints',
]

# Path to templates
templates_path = ['_templates']

# List of patterns to exclude from the build
exclude_patterns = []

# The language for content autogenerated by Sphinx
language = 'en'

# -- Options for HTML output -------------------------------------------------

html_theme = 'sphinx_rtd_theme'  # Read the Docs theme
html_static_path = ['_static']
